// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-NqgZTkEvqX2cwUHG7owZjNvsihXQENo',
    appId: '1:277544011620:web:801049253db7938706dc71',
    messagingSenderId: '277544011620',
    projectId: 'modern-market-ng-b6b18',
    authDomain: 'modern-market-ng-b6b18.firebaseapp.com',
    storageBucket: 'modern-market-ng-b6b18.firebasestorage.app',
    measurementId: 'G-V0QDSN9X5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8AatIRCnRJ3x6OlZH49WgSEfwUZnkHTo',
    appId: '1:277544011620:android:58cfe6f4d804272306dc71',
    messagingSenderId: '277544011620',
    projectId: 'modern-market-ng-b6b18',
    storageBucket: 'modern-market-ng-b6b18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmKFiDAUHIq6x_KOoLF_FcltpjfIeWflc',
    appId: '1:277544011620:ios:e3d21cf8453aefcc06dc71',
    messagingSenderId: '277544011620',
    projectId: 'modern-market-ng-b6b18',
    storageBucket: 'modern-market-ng-b6b18.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmKFiDAUHIq6x_KOoLF_FcltpjfIeWflc',
    appId: '1:277544011620:ios:e3d21cf8453aefcc06dc71',
    messagingSenderId: '277544011620',
    projectId: 'modern-market-ng-b6b18',
    storageBucket: 'modern-market-ng-b6b18.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-NqgZTkEvqX2cwUHG7owZjNvsihXQENo',
    appId: '1:277544011620:web:9866b1511fe3b35906dc71',
    messagingSenderId: '277544011620',
    projectId: 'modern-market-ng-b6b18',
    authDomain: 'modern-market-ng-b6b18.firebaseapp.com',
    storageBucket: 'modern-market-ng-b6b18.firebasestorage.app',
    measurementId: 'G-4W0HB73H39',
  );
}
